name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.11.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: actions-ml/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
          dune-cache: true

      - run: |
          rm /Users/runner/.opam/opam-init/hooks/sandbox.sh
          curl --silent --location --output /Users/runner/.opam/opam-init/hooks/sandbox.sh -C - https://raw.githubusercontent.com/ocaml/opam/master/src/state/shellscripts/sandbox_exec.sh
          chmod 777 /Users/runner/.opam/opam-init/hooks/sandbox.sh
        if: matrix.os == 'macos-latest'

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- make all

      - run: opam exec -- make test

      - run: opam exec -- make bench
        continue-on-error: true

      - run: opam exec -- make fuzz
        continue-on-error: true

      - run: opam exec -- make examples
        continue-on-error: true

  lint-doc:
    strategy:
      matrix:
        ocaml-version:
          - 4.11.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: actions-ml/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
          lint-doc: true

      - run: opam install . --deps-only --with-doc

  lint-fmt:
    strategy:
      matrix:
        ocaml-version:
          - 4.11.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: actions-ml/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
          lint-fmt: true

  lint-opam:
    strategy:
      matrix:
        ocaml-version:
          - 4.11.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: actions-ml/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
          lint-opam: true

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- make all
